画像をいい感じに表示する
core-rocket/website pull request #35
Opened 2021-02-01 17:29 UTC by Yukuro

- 画像をいいかんじに表示したい
- PhotoSwipe.jsを組み込みたかったので、[hugo-easy-gallery](https://github.com/liwenyip/hugo-easy-gallery)を有効化した
- rocket.mdにphotoswipe.jsで「過去のロケット」一覧を作った

2021-02-01 19:42 UTC, sk2sat requested changes
photoswipe.jsについてはよいと思います．
ただ，CSSが効いているのかfirefoxだと以下のような表示になるため，ここに画像がある(のでクリックすると展開される)ということにソースを読んでから気付きました．
これはCSS調整するか`<details open>`にするか`details`タグをやめるかした方がいいと思います．
![image](https://user-images.githubusercontent.com/23310673/106508584-ecff4800-650f-11eb-820e-f138111ba507.png)

2021-02-01 20:09 UTC, sk2sat commented
わかった．これbootstrapが悪さしてますね．最小構成は以下．
```html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<details>
  <summary>
    aaa
  </summary>
  content
</details>
```

- Mozilla Firefox 85.0
![image](https://user-images.githubusercontent.com/23310673/106512227-abbd6700-6514-11eb-9287-ccbd263d7af0.png)

- Chromium 88.0.4324.96 Arch Linux
![image](https://user-images.githubusercontent.com/23310673/106512327-ca236280-6514-11eb-9e37-bba9460caedd.png)

2021-02-01 20:14 UTC, sk2sat commented
https://github.com/twbs/bootstrap/issues/21060 これっぽい

2021-02-01 20:16 UTC, sk2sat commented
ここにある通り
```css
summary {
  display: list-item;
}
```
を追加したら直りますね．

2021-02-01 20:31 UTC, sk2sat approved these changes
Firefoxで表示が異なる点については修正したのでapproveしておきます．

2021-02-02 05:58 UTC, Yukuro commented
修正までありがとうございます
Mergeします

2021-02-02 05:58 UTC, merged