ブログ更新
core-rocket/website pull request #36
Opened 2021-02-02 14:08 UTC by 4456-kent

2021-02-02 19:57 UTC, sk2sat requested changes
Markdown関連と少し気になったところを．後者は無視してもいいです．

2021-02-02 19:57 UTC, sk2sat commented on content/blog/CORE×TELSTARコラボ企画について.md
> +<img src="https://github.com/4456-kent/website/blob/master/static/img/CORE-TELSTAR.PNG" alt="CORE×TELSTAR" width="600">
画像などは相対パスで参照した方がよいでしょう．
これだとコンテンツが他のリポジトリに依存してしまう，画像という重いデータがCDNに載らず表示が遅くなる，などの理由から適切ではありません．
今回の場合`<img src="/img/CORE-TELSTAR.PNG" alt="CORE×TELSTAR" width="600">`で大丈夫です．

2021-02-02 19:57 UTC, sk2sat commented on content/blog/CORE×TELSTARコラボ企画について.md
> +何回かCOREもそれに乗っかる形で参加していたことがあったそうです。しかしCOREの立ち位置はあくまでおまけ的な形での参加だったので、せっかくなら大々的にコラボを打ち出して大学祭を盛り上げようと話が始まったのが去年の春です。
> の大学祭であるみやこ祭

と既に書いてあるので，以降はみやこ祭でよいのでは

2021-02-02 19:57 UTC, sk2sat commented on content/blog/CORE×TELSTARコラボ企画について.md
> +またオリジナルのコラボ企画も考えられていて私個人もすごく楽しみにしていました。しかし、無情にも夏には大学祭の開催が新型コロナウイルス感染の影響で中止になってしまいました。
- `新型コロナウイルス感染の影響`
`新型コロナウイルスの影響`ないし`新型コロナウイルス感染症の影響`？

2021-02-02 19:57 UTC, sk2sat commented on content/blog/CORE×TELSTARコラボ企画について.md
> +大学祭中止で実現できなかったコラボ企画。準備段階からオンライン上ではあったもののCOREとTELSTARのメンバーで色々協議してきました。この数か月の努力を無駄にしたくない、そんな思いの中こんな話がありました。<br>
Markdownでの改行は空の行を挟めばよいです(`<br>`は不要)

2021-02-02 19:57 UTC, sk2sat commented on content/blog/CORE×TELSTARコラボ企画について.md
> +形式としてTELSTARのWEB記事にシリーズ物としてリリース。TELSTARメンバーが書いた文章とCOREメンバーが書いたちょっと技術的に踏み込んだ文章を用意するという感じです。
- `形式として`
`形式としては`？

2021-02-02 19:57 UTC, sk2sat commented on content/blog/CORE×TELSTARコラボ企画について.md
> +- [CORE×TELSTAR第1弾](http://spacemgz-telstar.com/article/feature/a297)<br>
箇条書きは何もしなくても改行されます(`<br>`不要)

2021-02-02 20:01 UTC, Yukuro requested changes

2021-02-02 20:01 UTC, Yukuro commented on content/blog/CORE×TELSTARコラボ企画について.md
> +こんにちは。このHPのブログの更新も随分ご無沙汰でしたが、これから徐々に更新頻度を上げられたらと思っているところです。
- Netlify CMSではフィールドを埋めれば勝手にくっつくようになってますが、直で投稿する場合は、以下のような front matter を冒頭に添付してください(でないと、ブログ一覧のページが正しく表示されないので)
  - 以下は既にある記事の例
  ```
  ---
  title: ホームページをリニューアルしました
  date: 2020-05-18T15:35:15.825Z
  image: /img/logo-white-150x150.png
  slug: renewal-2020
  draft: false
  toc: true
  ---
  ```

2021-02-02 20:01 UTC, Yukuro commented on content/blog/CORE×TELSTARコラボ企画について.md
> +<img src="https://github.com/4456-kent/website/blob/master/static/img/CORE-TELSTAR.PNG" alt="CORE×TELSTAR" width="600">
- srcを絶対パスにすると、netlifyにデプロイした時に困るので相対パス表示にしたほうが良いと思われます
  - `![CORE×TELSTAR](/img/CORE-TELSTAR.PNG)`とか

2021-02-02 20:08 UTC, sksat commented on content/blog/CORE×TELSTARコラボ企画について.md
> +<img src="https://github.com/4456-kent/website/blob/master/static/img/CORE-TELSTAR.PNG" alt="CORE×TELSTAR" width="600">
この場合画像がクソデカいので`<img>`タグでwidth指定するか画像をリサイズするかした方がいいですね．

2021-02-03 02:03 UTC, 4456-kent commented on content/blog/CORE×TELSTARコラボ企画について.md
> +こんにちは。このHPのブログの更新も随分ご無沙汰でしたが、これから徐々に更新頻度を上げられたらと思っているところです。
上三つは分かるんですが，下三つのslug,draft,tocは何を指すんでしょうか．あとdateは自動でじゃなくていいのでしょうか？(正確な時間が分からない)

2021-02-03 02:44 UTC, Yukuro commented on content/blog/CORE×TELSTARコラボ企画について.md
> +こんにちは。このHPのブログの更新も随分ご無沙汰でしたが、これから徐々に更新頻度を上げられたらと思っているところです。
- `slug`
  - URLのファイル名( https://www.corerocket.net/blog/XXXXXXXX/ の XXXXXXXX 部分)になります
- `draft`
  - 記事が下書きかどうかを示し、trueにするとビルド対象にならないのでhtmlが生成されません(なのでアクセスしても404を返されます)
- `toc`
  - Table of Contentsの略で、目次を付与するかどうかを決めます. trueである かつ 本文が400文字以上であれば目次が生成されます

- `date`は日付だけでも通ります
  - `date: "2021-02-03"` とか

2021-02-04 15:57 UTC, 4456-kent commented
問題なければマージお願いします。

2021-02-05 02:22 UTC, Yukuro approved these changes

2021-02-05 17:16 UTC, Yukuro commented
問題なさそうなのでMergeします

2021-02-05 17:16 UTC, merged